### ISSUE TITLE
Add a link to CONTRIBUTING.md for developers somewhere in the website

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch.github.io#1049]
The website has links for people who use the pytorch binary, but we should also include a link to the CONTRIBUTING.md (https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#developing-pytorch) for those who may want to contribute to OSS pytorch

**Comment by izaitsevfb** [comment]
FYI, the link to `CONTRIBUTING.md` is already present on the website (although, admittedly, it's not easy to reach):

Main → Resources → Contribution Guide → CONTRIBUTING.md

1.
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/108101595/180323669-6215d52e-5d7f-440b-b87b-7bcad463d82d.png">

2.
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/108101595/180323757-ac009619-2ee9-44f2-b88a-58d43dbc3d8f.png">

3.
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/108101595/180323807-87a45245-6444-4c0f-b2ff-40ed4ac585d8.png">

**Comment by janeyx99** [comment]
Interesting, the one linked here does NOT have the CONTRIBUTING.md https://pytorch.org/docs/stable/community/contribution_guide.html 
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/31798555/180324782-463e3387-d639-4dfb-ae2e-351692bfeb64.png">

**Comment by izaitsevfb** [comment]
There is also one direct link in a footer on the the main page:
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/108101595/180339075-6720381d-1bdf-4000-96eb-4a37f48fd6e2.png">

**Comment by izaitsevfb** [comment]
The direct link to `CONTRIBUTING.md` is present for the `master/unstable` version of the `contribution_guide`:
https://pytorch.org/docs/master/community/contribution_guide.html

However, it's missing in all the previous versions, including latest stable (1.12):
https://pytorch.org/docs/1.12/community/contribution_guide.html

This is because the docs section is automatically updated to reflect the `docs` in `pytorch/pytorch` : https://github.com/pytorch/pytorch/blob/master/docs/source/community/contribution_guide.rst

and the addition of the direct link to `CONTRIBUTING.md` was done only recently (see https://github.com/pytorch/pytorch/commit/8c8527233fc0e41145e351fb5fc72157280c2cb4).

**Comment by izaitsevfb** [comment]
To summarize,

There is a direct link to [CONTRIBUTING.md](http://contributing.md/) on the main page (in the footer). It can be easily found by doing a search for the text “contrib” on the main page.

In addition to that, the link to the “Contribution Guide” page is also present on the main page. The newest version of the guide (for main/unstable pytorch version) contains the direct link to the [CONTRIBUTING.md](http://contributing.md/) (prominently at the top). However, the older versions of the guide don’t have that link. The guide page (as the rest of the pytorch docs) on the site are automatically updated from the pytorch/pytorch repo, so I’m not sure if it’s wise to manually edit the pages for the older versions.

I think the recent addition (https://github.com/pytorch/pytorch/commit/8c8527233fc0e41145e351fb5fc72157280c2cb4) of the [CONTRIBUTING.md](http://contributing.md/) link to the “contribution guide” solves the issue, and we should wait for more feedback before attempting further actions.

Closing the issue for now.
