### ISSUE TITLE
Broken Link: Tensor Tutorial

### ISSUE THREAD

**Issue by mahamfkhan** [pytorch/pytorch.github.io#1151]
## 🕋 Website
 
The Tensor Tutorial is a broken link.

## To Reproduce

Steps to reproduce the behavior (if applicable):

1. Go to [tensor_tutorial](https://pytorch.org/beginner/blitz/tensor_tutorial.html). Link is broken.

## Screenshots
<img width="1391" alt="Screen Shot 2022-10-16 at 4 50 35 PM" src="https://user-images.githubusercontent.com/34014138/196045004-11d7fd70-b167-4337-afd1-f3fceb435a66.png">

## Desktop:

 - iOS
 - Chrome

**Comment by nashirj** [comment]
Adding on to this that all of these links are broken:
- https://pytorch.org/beginner/blitz/tensor_tutorial.html
- https://pytorch.org/beginner/blitz/autograd_tutorial.html
- https://pytorch.org/beginner/blitz/neural_networks_tutorial.html
- https://pytorch.org/beginner/blitz/cifar10_tutorial.html

They can be fixed by adding `tutorial/` between `.org/` and `beginner` in each of the links

**Comment by nashirj** [comment]
I would make a PR to fix it, but I'm not sure where the source for the page with the broken links (https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) is.

**Comment by svekars** [comment]
Thank you for reporting this issue. It has now been fixed.

**Comment by mahamfkhan** [comment]
Thank you!
