### ISSUE TITLE
Link preview is not working on Telegram, Twitter, Slack...

### ISSUE THREAD

**Issue by bittlingmayer** [pytorch/pytorch.github.io#14]
The HTML is somehow mal-formed, because none of the major platforms show a preview for the blog post links like http://pytorch.org/2018/01/19/a-year-in.html.

Optimisation for mobile is working (eg Firefox, which uses Readability), beyond that I have not investigated what the exact issue is.

Here is a screenshot from Telegram for macOS:

<img width="652" alt="screen shot 2018-01-24 at 18 58 52" src="https://user-images.githubusercontent.com/11457984/35338975-bb2bb432-0138-11e8-969b-c56c283a61e8.png">

**Comment by bittlingmayer** [comment]
In some sense this would complete https://github.com/pytorch/pytorch.github.io/pull/8.

**Comment by goodlux** [comment]
I think the issue here is that the blog pages don't currently support open graph meta data. 

This tool shows the issues, with the link you provided:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fpytorch.org%2F2018%2F05%2F02%2Froad-to-1.0.html

I just fixed the basics for the home page, I think it is relatively easy to do for the blog pages as well.
