### ISSUE TITLE
Broken Link to Faster R-CNN Source

### ISSUE THREAD

**Issue by AudreyBeard** [pytorch/pytorch.github.io#214]
The link `https://pytorch.org/docs/stable/_modules/torchvision/models/detection/faster_rcnn.html#fasterrcnn_resnet50_fpn`, specifically at `https://pytorch.org/docs/stable/torchvision/models.html#faster-r-cnn` is broken, and brings me to this page:

![image](https://user-images.githubusercontent.com/16946477/59112916-05b9f380-8912-11e9-9153-54416bef2118.png)

**Comment by jlin27** [comment]
Fixed with the 1.2 release. 

Source code now appears for 1.2: https://pytorch.org/docs/stable/_modules/torchvision/models/detection/faster_rcnn.html#fasterrcnn_resnet50_fpn

Source code for 1.1 (where issue was reported): https://pytorch.org/docs/1.1.0/_modules/torchvision/models/detection/faster_rcnn.html#fasterrcnn_resnet50_fpn
