### ISSUE TITLE
Installation recommends `soumith` conda channel

### ISSUE THREAD

**Issue by Kaixhin** [pytorch/pytorch.github.io#3]
The website is still set up ([via this file](https://github.com/pytorch/pytorch.github.io/blob/master/_data/wizard.yml)) to point to the `soumith` conda channel - but it seems that it's now available on the default channel. Should this be changed?

**Comment by soumith** [comment]
it's available via the default channel? how?

**Comment by Kaixhin** [comment]
Yeah actually this is pretty odd, and maybe my conda has gone weird somehow (running Ubuntu 14.04, conda with Python 3.6 and CUDA 8.0). Having run `conda install pytorch` previously, I now get:

```sh
conda install pytorch
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/ka709/miniconda3:
#
pytorch                   0.1.12                   py36_0
```

Versus:

```sh
conda install pytorch -c soumith
Fetching package metadata ...........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - soumith::pytorch-0.1.12-py361_2cu80
  - soumith::pytorch-0.1.12-py36_2cu80

Package plan for installation in environment /home/ka709/miniconda3:

The following packages will be UPDATED:

    pytorch: 0.1.12-py36_0 --> 0.1.12-py361_2cu80 soumith [cuda80]
```

Installing with `conda install pytorch -c soumith`, and then running `conda install pytorch` gives:

```sh
conda install pytorch
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/ka709/miniconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    pytorch: 0.1.12-py361_2cu80 soumith [cuda80] --> 0.1.12-py36_0
```

**Comment by soumith** [comment]
paging @kalefranz could I request you to please disable or remove the anaconda pytorch and pytorch-gpu packages? they are not fully done yet:

- they dont have an OSX builds
- they separately package CPU and GPU bits (which we absolutely don't recommend, it's confusing to the user in many ways. If you insist `pytorch` has to have GPU support and `pytorch-cpu` has to be the CPU only build)
- the packages only are build against CUDA 7.5, we need to provide CUDA 7.5 and CUDA 8.0 versions because 7.5 doesn't support newer cards.
- We don’t want to ship nomkl packages. PyTorch without a good BLAS library crawls on the CPU side, and doesn’t have LAPACK routines enabled.

Jonathan sent me an email about these packages a couple of months ago (when they were private), but I didn't get time to look into his package scripts yet (i am a bit overworked, but it is on my TODO list). **Someone made these packages public on the anaconda side a couple of days ago .**
Reference URL: https://anaconda.org/anaconda/pytorch/files

**Comment by Kaixhin** [comment]
Yep if I just want to naively do `conda update --all` now then I get:

```sh
The following packages will be SUPERSEDED by a higher-priority channel:

    pytorch:     0.2.0-py36h6d07548_2cu80 soumith [cuda80] --> 0.1.12-py36cuda7.5cudnn6.0_1
    torchvision: 0.1.9-py36h7584368_1     soumith --> 0.1.8-py36_0
```

Looking at the download count, people are actually pulling these new packages (uploaded 4 days ago).

**Comment by soumith** [comment]
reported this to the conda folks :(
There's not much I can do other than reporting it to them, and they're slow in issuing new packages (their staging / testing process takes some time), and they dont have Cuda8 support yet.

**Comment by saraswat** [comment]
So what is the recommended process? I see on the pytorch page that `-c south` is still recommended. However, I am working in a context where proxy blocks access to `https://conda.anaconda.org/soumith/linux-64/repodata.json` but not to the default channels. I care just about a CPU version on RHL 6.7 (for now) -- though of course I would prefer pytorch with optimized libraries. Should I go ahead and use the default channel?

**Comment by soumith** [comment]
the default channel has 0.1.12 which is a very old channel. if you only require CPU and you have access only to default channel, build from source: https://github.com/pytorch/pytorch#from-source
