### ISSUE TITLE
RC Docs Build includes the z version in the UI and title

### ISSUE THREAD

**Issue by brianjo** [pytorch/pytorch.github.io#929]
## 📚 Documentation

Our 1.11 RC docs build is going to the correct folder /docs/1.11/ but the version number in the UI and the title still includes .0 at the end. For 1.11, we'll not be specifying the semver patch version number in the docs.  @mattip could you take a look at the build script and make any required changes?

Here's the RC 2 output: https://pytorch.org/docs/1.11/

Thanks!

cc: @holly1238 @malfet

**Comment by mattip** [comment]
I think this is due to the `torch.__version__` parsing in the sphinx `conf.py` which starts with [`torch_version = str(torch.__version__)`](https://github.com/pytorch/pytorch/blob/4737ae7a16e75958efd8e0177af8a1b570e9227d/docs/source/conf.py#L313) (which will get `1.11.0`), then this is used as the version without trimming off the `.0`
